### PR TITLE
Reverts the Alpine Linux changes introduced

### PR DESCRIPTION
**Pull request by gdams**
Closes: https://github.com/adoptium/jdk8u/issues/11

Reverts https://github.com/adoptium/jdk8u/pull/9 and https://github.com/adoptium/jdk8u/pull/10

CC @calderast as you made the original commits.

The plan is to move these into a separate repo called `alpine-jdk8u`

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Going by the comparison of the result with master, this looks correct. Only contains the company name patch and some other things we need for compliance. No more musl port patches AFAIK.

https://github.com/adoptium/jdk8u/compare/master...gdams:jdk8u_skara:revert?expand=1

**Comment by calderast** [comment]
All changes being reverted here match the changes added in #9 and #10 with nothing missed. LGTM as long as the build passes basic tests

**Comment by gdams** [comment]
Created a GitLab issue to create a new alpine repo (https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2480)

**Review by karianna — APPROVED** [review]
LGTM

**Comment by gdams** [comment]
@calderast do you want to raise the PR with the patches to the `release` branch at https://github.com/adoptium/alpine-jdk8u?

**Pull request merged**
